import type { Metadata } from "next";
import localFont from "next/font/local";
import {Footer} from "../components"
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import 'react-multi-carousel/lib/styles.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "M AND A Industries",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <section className=' bg-black padding-x padding-t pb-8'>
        <Footer />
      </section>

      <script src="https://static.elfsight.com/platform/platform.js" async></script>
      <div className="elfsight-app-b63c37aa-aa31-4ec3-8d2c-504e6db54396" data-elfsight-app-lazy></div>

      </body>
    </html>
  );
}
